### ISSUE TITLE
Request for New Release on RubyGems

### ISSUE THREAD

**Issue by navidemad** [whomwah/rqrcode#149]
I hope you are doing well. Thank you for all the hard work you’ve put into maintaining this gem.

I noticed that there have been several commits merged into the main branch.
However, these changes haven’t been published as a new release on RubyGems yet.

Would it be possible to make a new release so that we can take advantage of the latest improvements via RubyGems?
It would be greatly appreciated.

Thank you for considering this

**Comment by whomwah** [comment]
Hi @navidemad,

I'm actually working on a release mainly due to a changes in `rqrcode_core` I've been looking at but I don't have a time frame as I only get to work on this project in my spare time.

If you look at the diff between that latest release and `main` https://github.com/whomwah/rqrcode/compare/v2.2.0...master you can see that none of the changes pertain to functionality and are all changes to tooling and admin.

Thanks,
D
