### ISSUE TITLE
Make chunky_png dependency optional?

### ISSUE THREAD

**Issue by olivierlacan** [whomwah/rqrcode#40]
Would it be possible to make this runtime dependency optional when using the PNG renderer? We have no use for PNG rendering and would like to avoid taking on an extra transitive dependency since SVG is supported in all major browsers: http://caniuse.com/#feat=svg

Thanks for this gem by the way, it looks very well-maintained. :-)

**Comment by bjornblomqvist** [comment]
Do you have good idea of how to do this? I would guess that most people use png for rendering. So removing it would mean breaking the API.

**Comment by bjornblomqvist** [comment]
@olivierlacan is this still an issue?

**Comment by olivierlacan** [comment]
No

**Comment by monfresh** [comment]
If you're adhering to [semantic versioning](http://semver.org/), you can make this change whenever you want since you haven't reached version 1.0 yet. Anyone using a gem that is using semantic versioning and that is still in version `0.x` is implicitly acknowledging that breaking changes may occur at any time.
 
One easy way to do this would be to remove the dependency from the gemspec, release a new version, and update the README to state that if you want to use PNG rendering, you need to add `chunky_png` to your Gemfile. This change would also be noted in your CHANGELOG.

Note that your API will only break for users who upgrade to the new version that removes the dependency without reading the documentation. I personally never upgrade a gem without seeing what changes were made. As long as the changes are documented, I don't see why you can't remove the dependency in a future version.

**Comment by bjornblomqvist** [comment]
Semantic versioning being able to trust that things wont break when upgrading. That rqrcode is still on major version 0 does not mean that its unstable and that one should expect things to break. Its been working for many years without breaking! I myself have been using rqrcode since ~ 0.4.2 in production and I would be breaking my own projects if i made that change without also bumping the major version as i have been using ~> 0.4 in my gemfiles.

Versions are cheap.. If we really want this we could bump the major version. But, i don't really think there is much interest in removing chunky_png. I have only hear from one user so far.
